apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-rnu7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-rnu7
    app.kubernetes.io/part-of: quarkus
  name: devfile-sample-code-with-quarkus-rnu7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-rnu7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-rnu7
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-qlaw-tenant/quarkus/devfile-sample-code-with-quarkus-rnu7@sha256:4b20542d6eb011bf6067f83d5947611b9c4e14f5c51835a9d0138ad683929567
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
